blockchain:
   #区块链db路径
  BlockDbPath: "./data1/blocks"
  #区块链KeyStoragePath
  KeyStoragePath: "./data1/keys"
network:
  #本地RPC监听端口
  RPCListenAddress: "127.0.0.1:9005"
  #客户端监听端口
  ClientAPIAddress: "127.0.0.1:9005"
    #协议类型
  protocol_type: "http://"
  #p2p网络监听端口
  P2PListenAddress: ":9004"
  #p2p bootstrap
  P2PBootstraps:
    - "127.0.0.1:9001"
  #版本
  ProtocolVersion: 0
  #网络ID
  NetworkID: 0
  #签名 crt
  server_crt: ""
  #https key
  server_key: ""




  

